import { NextRequest, NextResponse } from "next/server";
import { prisma } from "@/lib/prisma";
import { z } from "zod";

import { generateSop } from "@/lib/sop/generationPipeline";




const CreateSopSchema = z.object({
  department: z.string().min(1),
  category: z.string().min(1),
  processDescription: z.string().min(1),

  // sources
  prompt: z.string().optional(),
  policyText: z.string().optional(),
  regulationText: z.string().optional(),
  meetingNotes: z.string().optional(),
  processMap: z.string().optional(),
  extractedPdfText: z.string().optional(),

  code: z.string().optional(),
  title: z.string().optional(),
});

export async function POST(request: NextRequest) {
  // MVP: no auth/tenant wiring yet; tenant inferred from env fallback.
  // If your app has auth helpers, we will swap this in later.
  const tenantId = process.env.DEFAULT_TENANT_ID ?? "dev";

  let body: z.infer<typeof CreateSopSchema>;
  try {
    body = CreateSopSchema.parse(await request.json());
  } catch {
    return NextResponse.json({ error: "Invalid request body" }, { status: 400 });
  }

  const sopCode = body.code ?? `${body.category}-${body.department}`.replace(/\s+/g, "-").toUpperCase();
  const title = body.title ?? `${body.category} SOP`;
  const createdBy = "system";

  const genInput = {
    department: body.department,
    category: body.category,
    processDescription: body.processDescription,
    prompt: body.prompt,
    policyText: body.policyText,
    regulationText: body.regulationText,
    meetingNotes: body.meetingNotes,
    processMap: body.processMap,
    extractedPdfText: body.extractedPdfText,
    code: sopCode,
    title,
  };

  try {
    const output = await generateSop(genInput);

    // upsert sop
    const sop = await prisma.sop.upsert({
      where: { tenantId_code: { tenantId, code: sopCode } },
      update: {
        title,
        department: body.department,
        category: body.category as any,
        status: "DRAFT",
      },
      create: {
        tenantId,
        department: body.department,
        code: sopCode,
        title,
        category: body.category as any,
        status: "DRAFT",
        currentVersion: 1,
        createdBy,
      },
    });

    const nextVersion = (sop.currentVersion ?? 0) + 1;

    const createdVersion = await prisma.sopVersion.create({
      data: {
        sopId: sop.id,
        version: nextVersion,
        status: "DRAFT",
        changes: `Auto-generated by SOP pipeline (version ${nextVersion})`,
        content: output.structure as any,
        outline: output.structure as any,
        sla: output.structure?.sla as any,
        complianceFindings: output.agentFindings as any,
        riskFindings: output.agentFindings as any,
        auditFindings: output.agentFindings as any,
        complianceScore: output.agentFindings.complianceScore,
        riskScore: output.agentFindings.riskScore,
        auditReadinessScore: output.agentFindings.auditReadinessScore,
        approvedBy: null,
        approvedAt: null,
      },
    });

    await prisma.sop.update({
      where: { id: sop.id },
      data: { currentVersion: nextVersion },
    });

    // artifacts
    const artifactsData = [
      { type: "MARKDOWN", title: "Markdown", content: output.artifacts.markdown ?? "" },
      { type: "HTML", title: "HTML", content: output.artifacts.html ?? "" },
      { type: "MERMAID", title: "Mermaid", content: output.artifacts.mermaid ?? "" },
    ];

    await prisma.sopArtifact.createMany({
      data: artifactsData.map((a) => ({
        versionId: createdVersion.id,
        type: a.type as any,
        title: a.title,
        content: a.content,
      })),
      skipDuplicates: true,
    });

    // audit event (MVP)
    // persist risks/compliance/approvals (MVP)
    const risksToCreate = [
      {
        versionId: createdVersion.id,
        riskLevel: "MEDIUM",
        risk: output.agentFindings.issues?.[0] ?? "Identified risk (MVP)",
        likelihood: "MEDIUM",
        impact: "MEDIUM",
        mitigation: "Follow SOP and escalate issues",
      },
    ];

    const complianceToCreate = [
      {
        versionId: createdVersion.id,
        requirement: output.structure?.complianceRequirements?.[0]?.requirement ?? "Baseline compliance requirement",
        regulation: output.structure?.complianceRequirements?.[0]?.regulation,
        control: output.structure?.complianceRequirements?.[0]?.control,
        status: output.structure?.complianceRequirements?.[0]?.status,
      },
    ];

    const approvalsToCreate = (output.structure?.approvals ?? []).map((a) => ({
      versionId: createdVersion.id,
      approverRole: a.approverRole,
      approverName: null,
      status: "PENDING",
      comment: null,
      decidedBy: null,
      decidedAt: null,
    }));

    await prisma.sopRiskItem.createMany({ data: risksToCreate as any, skipDuplicates: true });
    await prisma.sopComplianceItem.createMany({ data: complianceToCreate as any, skipDuplicates: true });
    if (approvalsToCreate.length) {
      await prisma.sopApproval.createMany({ data: approvalsToCreate as any, skipDuplicates: true });
    }

    // audit event (MVP)
    await prisma.sopAuditEvent.create({
      data: {
        versionId: createdVersion.id,
        actor: createdBy,
        action: "SOP_VERSION_SAVED",
        evidence: { outputScores: output.agentFindings },
      },
    });

    return NextResponse.json({
      sopId: sop.id,
      versionId: createdVersion.id,
      sopCode: output.sopCode,
      title: output.title,
      version: createdVersion.version,
    });
  } catch (error) {
    console.error(error);
    return NextResponse.json({ error: "SOP generation failed" }, { status: 500 });
  }
}

